export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD';
export const RECEIVED_FORGOT_PASSWORD = 'RECEIVED_FORGOT_PASSWORD';
export const RECEIVED_FORGOT_PASSWORD_ERROR = 'RECEIVED_FORGOT_PASSWORD_ERROR';