export const REQUEST_APPROVAL_DATA = 'REQUEST_APPROVAL_DATA';
export const RECEIVED_APPROVAL_DATA = 'RECEIVED_APPROVAL_DATA';
export const RECEIVED_APPROVAL_DATA_ERROR = 'RECEIVED_APPROVAL_DATA_ERROR';
