export const REQUEST_BANKING_DETAILS_DATA = 'REQUEST_BANKING_DETAILS_DATA';
export const RECEIVED_BANKING_DETAILS_DATA = 'RECEIVED_BANKING_DETAILS_DATA';
export const RECEIVED_BANKING_DETAILS_DATA_ERROR = 'RECEIVED_BANKING_DETAILS_DATA_ERROR';