export const REQUEST_CATEGORY = 'REQUEST_CATEGORY';
export const RECEIVED_CATEGORY = 'RECEIVED_CATEGORY';
export const RECEIVED_CATEGORY_ERROR = 'RECEIVED_CATEGORY_ERROR';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';