export const REQUEST_LICENSE_DETAILS_DATA = 'REQUEST_LICENSE_DETAILS_DATA';
export const RECEIVED_LICENSE_DETAILS_DATA = 'RECEIVED_LICENSE_DETAILS_DATA';
export const RECEIVED_LICENSE_DETAILS_DATA_ERROR = 'RECEIVED_LICENSE_DETAILS_DATA_ERROR';