export const REQUEST_CUSTOMER_REGISTER = 'REQUEST_CUSTOMER_REGISTER';
export const RECEIVED_CUSTOMER_REGISTER = 'RECEIVED_CUSTOMER_REGISTER';
export const RECEIVED_CUSTOMER_REGISTER_ERROR = 'RECEIVED_CUSTOMER_REGISTER_ERROR';