export const REQUEST_SITE_DETAILS_DATA = 'REQUEST_SITE_DETAILS_DATA';
export const RECEIVED_SITE_DETAILS_DATA = 'RECEIVED_SITE_DETAILS_DATA';
export const RECEIVED_SITE_DETAILS_DATA_ERROR = 'RECEIVED_SITE_DETAILS_DATA_ERROR';