export const REQUEST_UPDATE_BASICINFO = 'REQUEST_UPDATE_BASICINFO';
export const RECEIVED_UPDATE_BASICINFO = 'RECEIVED_UPDATE_BASICINFO';
export const RECEIVED_UPDATE_BASICINFO_ERROR = 'RECEIVED_UPDATE_BASICINFO_ERROR';
