export const REQUEST_UPLOADVOIDCHECK = 'REQUEST_UPLOADVOIDCHECK';
export const RECEIVED_UPLOADVOIDCHECK = 'RECEIVED_UPLOADVOIDCHECK';
export const RECEIVED_UPLOADVOIDCHECK_ERROR = 'RECEIVED_UPLOADVOIDCHECK_ERROR';
