export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD';
export const RECEIVED_RESET_PASSWORD = 'RECEIVED_RESET_PASSWORD';
export const RECEIVED_RESET_PASSWORD_ERROR = 'RECEIVED_RESET_PASSWORD_ERROR';