export const REQUEST_SET_PASSWORD = 'REQUEST_SET_PASSWORD';
export const RECEIVED_SET_PASSWORD = 'RECEIVED_SET_PASSWORD';
export const RECEIVED_SET_PASSWORD_ERROR = 'RECEIVED_SET_PASSWORD_ERROR';

export const REQUEST_VERIFY_TOKEN = 'REQUEST_VERIFY_TOKEN';
export const RECEIVED_VERIFY_TOKEN = 'RECEIVED_VERIFY_TOKEN';
export const RECEIVED_VERIFY_TOKEN_ERROR = 'RECEIVED_VERIFY_TOKEN_ERROR';